"""
Django settings for woowoo_webapp project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from settings_secret import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_URL = 'http://app.waterlesstoilets.co.uk/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENVIRONMENT_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [u'app.waterlesstoilets.co.uk']

#KASHFLOW TEST
KF_TEST_RECIPIENT_ID = "4580634"
KF_TEST_RECIPIENT_NAME = "Test"
KF_TEST_EMAIL = 'joel@waterlesstoilets.co.uk'

# Application definition

INSTALLED_APPS = [
    'django_mailbox',
    'django_premailer',
    'bootstrapform',
    'emails.apps.EmailsConfig',
    'installations.apps.InstallationsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = 'woowoo_webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'woowoo_webapp.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '/home/joelcormack/woowoo_webapp/woowoo/woowoo_webapp/woowoo_webapp/static/'
STATICFILES_DIRS = (
        os.path.join(BASE_DIR,'static'),
        )
# Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# django-mailbox
DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO='mailbox_attachments/'

#ZOHO VALUE MAPPINGS
"""ZOHO CRM maped --> app variables"""
POTENTIAL_TO_INSTALLATION = {
            'POTENTIALID':'potential_id',
            'Potential Name':'potential_name',
            'Site Street':'site_address',
            'Site Street 2':'site_address_two',
            'Site City':'site_city',
            'Site County':'site_county',
            'Site Post Code':'site_postcode',
            'Installation Method':'install_method',
            'Google Maps Link':'gmap_link',
            'Forklift Available':'forklift',
            'Installation Location (51.634759, -0.179661)':'long_lat',
            'CONTACTID':'contact_id'}
PRODUCTS = { 'KL1':'KL1',
            'KL2 prm':'KL2 prm',
            'KL3':'KL3',
            'STK':'STK',
            'KLu':'KLu'}
ZOHO_CONTACT_TO_CONTACT = {
            'CONTACTID' : 'contact_id',
            'First Name': 'first_name',
            'Last Name': 'last_name',
            'Phone (main)' : 'phone',
            'Email': 'email'}
