# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('installation_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('contractor_confirmed', models.BooleanField(default=False)),
                ('haulier_confirmed', models.BooleanField(default=False)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('retailer_confirmed', models.BooleanField(default=False)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address_one', models.CharField(max_length=50)),
                ('address_two', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='sites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Site'),
        ),
    ]
