# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address_one', models.CharField(max_length=50)),
                ('address_two', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('provisional_date', models.DateField(null=True)),
                ('installation_date', models.DateField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('pickup_date', models.DateField(null=True)),
                ('contractor_confirmed', models.BooleanField(default=False)),
                ('haulier_confirmed', models.BooleanField(default=False)),
                ('haulier_receipt', models.FileField(null=True, upload_to='haulier_receipts/%Y/%m/%d')),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('retailer_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('K1', 'KL1'), ('K2', 'KL2 prm'), ('K3', 'KL3'), ('Ku', 'KL Urinal'), ('ST', 'STK')], max_length=2, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation'),
        ),
    ]
