# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('K1', 'KL1 + STK'), ('K2', 'KL2 prm + STK'), ('K3', 'KL3 + STK'), ('Ku', 'KL Urinal'), ('ST', 'STK')], max_length=2, null=True),
        ),
    ]
