# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_auto_20151219_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
    ]
