# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_auto_20160114_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='haulier_confirmed',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='haulier_receipt',
        ),
        migrations.AddField(
            model_name='installation',
            name='supplier_receipt',
            field=models.FileField(null=True, upload_to='supplier_receipts/%Y/%m/%d'),
        ),
    ]
