# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0005_auto_20160115_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='supplier_receipt',
        ),
        migrations.AddField(
            model_name='installation',
            name='shipping_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installation',
            name='shipping_receipt',
            field=models.FileField(null=True, upload_to='shipping_receipts/%Y/%m/%d'),
        ),
    ]
