# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_auto_20160115_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='forklift_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installation',
            name='gmaps_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_method',
            field=models.CharField(choices=[('SI', 'Self Install'), ('CI', 'Contractor Install'), ('GG', 'GGM Install'), ('SG', 'Self Install with GGM Assistance')], default='SI', max_length=2),
        ),
    ]
