# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_auto_20160120_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='has_forklift',
        ),
    ]
