# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0008_remove_installation_has_forklift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('K1', 'KL1'), ('K2', 'KL2 prm'), ('K3', 'KL3'), ('Ku', 'KLu'), ('ST', 'STK')], max_length=20, null=True),
        ),
    ]
