# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0009_auto_20160120_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
