# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0012_auto_20160310_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='provisional_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
